# host_vars/pr001.yml
---
#bind configuration
#opzetten domein
bind_zone_domains:
  - name: "avalon.lan" #naar '@' zetten indien je naar 'example.com' wilt surfen
    hosts:
      - name: pr001
        ip: 172.16.192.1
        aliases:
          - ns1
      - name: pr002
        ip: 172.16.192.2
        aliases:
          - ns2
      - name: pu001
        ip: 192.0.2.10
        aliases:
          - www
      - name: pu002
        ip: 192.0.2.20
        aliases:
          - mail
    networks:
      - "172.16"
      - "10"
    delegate:
      - zone: foo
        dns: 172.16.192.1
bind_zone_master_server_ip: 172.16.192.1

bind_forwards:
  - 8.8.8.8
  - 8.8.4.4

#acl aanmaken 
bind_acls:
  - name: acl1
    match_list:
      - 192.0.2.0/24
      - 10.0.0.0/8
bind_dns_keys:
  - name: master_key
    algorithm: hmac-sha256
    secret: "admin"

bind_listen_ipv4:
  - any
bind_allow_query:
  - any
rhbase_firewall_allow_services:
  - dns
