# host_vars/pr002.yml
---
#bind configuration
bind_zone_domains:
  - name: "avalon.lan"
    networks:
      - "172.16"
      - "192.0.2"
      - "10"

bind_forwards:
  - 8.8.8.8
  - 8.8.4.4

bind_zone_master_server_ip: 172.16.192.1

bind_listen_ipv4:
  - any
bind_allow_query:
  - any
rhbase_firewall_allow_services:
  - dns