# host_vars/pr001
---
#bind configuration

bind_zone_domains:
  - name: "avalon.lan" #naar '@' zetten indien je naar 'example.com' wilt surfen
    hosts:
      - name: pr001
        ip: 172.16.192.1
        aliases:
          - ns
      - name: pu001
        ip: 192.0.2.10
        aliases:
          - www
    networks:
      - "172.16"
      - "10"
      - "192.0.2"

bind_acls:
  - name: acl1
    match_list:
      - 192.0.2.0/24
      - 10.0.0.0/8
bind_dns_keys:
  - name: master_key
    algorithm: hmac-sha256
    secret: "admin"
bind_extra_include_files:
  - "{{ bind_auth_file }}"

bind_zone_master_server_ip: 172.16.192.1

bind_listen_ipv4:
  - any
bind_allow_query:
  - any
rhbase_firewall_allow_services:
  - dns
