# host_vars/pr002.yml
---
#bind configuration
bind_zone_domains:
  - name: "avalon.lan"
    networks:
      - "172.16"
      - "192.0.2"
    name_servers:
      - pr001
      - pr002
bind_zone_master_server_ip: 172.16.192.1
#dynamic updates
bind_zone_file_mode: '0660'
bind_listen_ipv4:
  - any
bind_allow_query:
  - any
rhbase_firewall_allow_services:
  - dns


