# host_vars/pr001.yml
---
#bind configuration
#opzetten domein
bind_zone_domains:
  - name: "avalon.lan" #naar '@' zetten indien je naar 'example.com' wilt surfen
    hosts:
      - name: pr001
        ip: 172.16.192.1
        aliases:
          - ns1
      - name: pr002
        ip: 172.16.192.2
        aliases:
          - ns2
      - name: pu001
        ip: 192.0.2.10
        aliases:
          - www
      - name: pu002
        ip: 192.0.2.20
        aliases:
          - mail
      - name: pr003
        ip: 172.16.192.3
        aliases:
          - dhcp
      - name: pr004
        ip: 172.16.192.4
        aliases:
          - directory 
      - name: pr010
        ip: 172.16.192.10
        aliases:
          - inside
      - name: pr011
        ip: 172.16.192.11
        aliases:
          - files    
    networks:
      - "172.16"
      - "192.0.2"
    name_servers:
      - pr001
      - pr002
    mail_servers:
      - name: pu002 
        preference: 10
    services:
      - name: _ldap._tcp
        weight: 100
        port: 53
        target: pr002
    delegate:
      - zone: avalon.lan
        dns: 172.16.192.1
    
bind_zone_master_server_ip: 172.16.192.1
bind_zone_dir: /var/named
bind_forwarders:
  - '8.8.8.8'
  - '8.8.4.4'
#acl aanmaken 
bind_acls:
  - name: acl1
    match_list:
    - 172.16.0.0/16  
    - 192.0.2.0/24   
bind_dns_keys:
  - name: master_key
    algorithm: hmac-sha256
    secret: "admin"
bind_listen_ipv4:
  - any
bind_allow_query:
  - any
rhbase_firewall_allow_services:
  - dns