# host_vars/pr001.yml
---
#rhbase configuration
rhbase_firewall_allow_services:
  - dhcp
#dhcp configuration
#master en slave dns ingeven
dhcp_global_domain_name_servers:
  - 172.16.192.1 #dns1
  - 172.16.192.2 #dns2

dhcp_global_default_lease_time: 43200
dhcp_global_max_lease_time: 43200
dhcp_global_domain_name: avalon.lan
dhcp_global_bootp: allow
dhcp_global_booting: allow
dhcp_global_routers: 192.0.2.254
dhcp_global_classes:
  - name: vbox
    match: 'match if binary-to-ascii(16,8,":",substring(hardware, 1, 3)) = "8:0:27"'
dhcp_subnets:
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    routers: 172.16.255.254
    pools:
      - default_lease_time: 14400
        max_lease_time: 14400 #4 uur
        range_begin: 172.16.0.2
        range_end: 172.16.127.254                 
      - range_begin: 172.16.192.1
        range_end: 172.16.255.253     
dhcp_hosts:
  #- name: pr011
  #  mac: '08:00:27:64:5B:11'
  #  ip: 172.16.192.11


