# host_vars/pr001.yml
---
#rhbase configuration
rhbase_firewall_allow_services:
  - dhcp
#dhcp configuration
#master en slave dns ingeven
dhcp_global_domain_name_servers:
  - 172.16.192.1 #dns1
  - 172.16.192.2 #dns2

dhcp_global_default_lease_time: 43200
dhcp_global_max_lease_time: 43200
dhcp_global_domain_name: avalon.lan
dhcp_global_bootp: allow
dhcp_global_booting: allow
dhcp_global_classes:
  - name: vbox
    match: 'match if binary-to-ascii(16,8,":",substring(hardware, 1, 3)) = "8:0:27"'
dhcp_subnets:
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    routers: 172.16.255.254
    pools:     
      - range_begin: 172.16.0.2
        range_end: 172.16.127.254     
        deny: 'members of "vbox"'
      - range_begin: 172.16.128.1
        range_end: 172.16.191.254
        allow: 'members of "vbox"'
#uit-commenten indien aanmaken manueel VBox voor dhcp te testen (op werkstation)
#dhcp_hosts:
  #- name: testbox
    #mac: '08:00:27:B4:64:01'
    #ip: 172.16.0.10