# host_vars/pu001.yml
---
#rh-base configuratie
rhbase_firewall_allow_services: 
  - http
  - https
#mariadb configuratie
mariadb_root_password: 'fogMeHud8' 
mariadb_databases:
  - name: wp_db
mariadb_users:
  - name: wp_user
    password: CorkIgWac
    priv: 'wp_db.*:ALL'
    append_privs: yes
#Wordpress configuratie
wordpress_database: wp_db
wordpress_user: wp_user
wordpress_password: CorkIgWac
#httpd configuratie
httpd_ssl_certificate_file: 'ca.crt'
httpd_ssl_certificate_key_file: 'ca.key'
#rkhunter configuratie
rkhunter_diag_scan: "yes"
#lynis configuration
lynis_deploy_method: "git"
lynis_report_from: 'dylano.steenhuyzen@hotmail.com'
lynis_report_to: 'dylano.steenhuyzen.y4659@student.hogent.be'