# host_vars/pu001.yml
---
#rh-base configuratie
rhbase_firewall_allow_services: 
  - http
  - https
#mariadb configuratie
mariadb_root_password: 'fogMeHud8' 
mariadb_databases:
  - name: wp_db
mariadb_users:
  - name: wp_user
    password: CorkIgWac
    priv: 'wp_db.*:ALL'
    append_privs: yes
#Wordpress configuratie
wordpress_database: wp_db
wordpress_user: wp_user
wordpress_password: CorkIgWac
#httpd configuratie
httpd_ssl_certificate_file: 'ca.crt'
httpd_ssl_certificate_key_file: 'ca.key'

#OP TE LOSSEN ERROR: geen connectie met 192.0.2.10/wordpress
#Dit KAN komen doordat het certificaat de naam 'Dylano' heeft en niet '192.0.2.10'
##   (mogelijke)   OPLOSSING     ##
# Nieuw ceritficaat laten genereren met CN/naam = 192.0.2.10
