# roles/rh-base/defaults/main.yml
---

# Package management
rhbase_repositories: epel-release

rhbase_repo_update_type: default
rhbase_repo_random_sleep: 360
rhbase_repo_updates_download: true
rhbase_repo_updates_apply: true
rhbase_repo_emit_via: stdio
rhbase_repo_email_from: root@localhost
rhbase_repo_email_to: root
rhbase_repo_email_host: localhost

# Services
rhbase_start_services: 
  - firewalld
  - systemd-journald.service
  - yum-cron
  - sshd
  
# Security
rhbase_firewall_allow_services: 
  - http
  - https

rhbase_firewall_allow_ports: 
  - 22/tcp
  - 8081/tcp
  - 161-162/udp

rhbase_firewall_interfaces: 
  - eth0
  - eth1

rhbase_selinux_state: enforcing
rhbase_selinux_booleans: 'httpd_can_network_connect'