# host_vars/pu00.yml
---

#rh-base configuratie
rhbase_firewall_allow_services:
  - imap
  - imaps
  - pop3
  - pop3s
  - smtp
  - smtps
  - smtp-submission

rhbase_firewall_allow_ports:
  - 25/tcp #SMTP port
  - 587/tcp #SMTP port voor abuse port 25
  - 110/tcp #POP port
  - 995/tcp #POPS port
  - 143/tcp #IMAP port
  - 993/tcp #IMAPs port

rhbase_users:
  - name: dylano
    password: '$1$mmHR2KDR$Bflb5h9Vh87PgO7atJhpZ0'
    shell: /sbin/nologin

rhbase_hosts_entry: true

#mail configuratie
#verdere uitwerking na afwerking ftp server
#dan moeten de volgende variabelen geinitialiseerd worden:
#postfix_ldap: true dan MOET men deze ook definieren:
#ldap_fqdn1,ldap_Ou,ldap_dcname,ldap_domainname,ldap_root_domain
