# roles/rh-base/defaults/main.yml
---

## rh-base configuratie ##

# Package management
rhbase_repo_update_type: default
rhbase_repo_random_sleep: 360
rhbase_repo_updates_download: true
rhbase_repo_updates_apply: true
rhbase_repo_emit_via: stdio
rhbase_repo_email_from: root@localhost
rhbase_repo_email_to: root
rhbase_repo_email_host: localhost

# Services 
rhbase_start_services: 
  - firewalld
  - systemd-journald.service
  - yum-cron
  - sshd
  
# Security
rhbase_firewall_allow_services: 
  - http
  - https

rhbase_firewall_allow_ports: 
  - 22/tcp #port 22 voor ssh
  - 8081/tcp
  - 161-162/udp

rhbase_firewall_interfaces: 
  - eth0
  - eth1

rhbase_selinux_state: enforcing
rhbase_selinux_booleans: 'httpd_can_network_connect'

## mariadb configuratie ##
mariadb_bind_adress: '0.0.0.0'

mariadb_root_password: fogMeHud8 

mariadb_users:
  - name: dylano
    password: Str0ngp4ssw0rd
    priv: '*.*:ALL'
    host: '%'
  - name: wp_user
    password: CorkIgWac
    priv: 'wp_db.*:ALL'
    host: '192.0.2.%'

## Wordpress configuratie ##
wordpress_database: wp_db
wordpress_user: wp_user
wordpress_password: CorkIgWac

## httpd configuratie ##
httpd_ssl_certificate_file:  /vagrant/ansible/certificates/ca.crt
httpd_ssl_certificate_key_file: /vagrant/ansible/certificates/ca.key