
#enable firewall
   - name: Set dmz as default policy
      command: firewall-cmd --set-default-zone=dmz

   - name: Allow http/https
      command: firewall-cmd --zone=dmz --permanent --add-service=http --add-service=https

 
#status van SELinux naar 'Enforcing' veranderen
  - name: Enable libselinux-python for Ansible
    yum: name=libselinux-python state=installed  

  - name: Enable SELinux
    selinux:
         policy: targeted
         state: enforcing

#Toevoegen van de epel repositories  
  - name: Set yum configuration
    template: src=yum.conf.j2 
              dest=/etc/yum.conf

  - name: Copy local repo conf file
    template: src=Centos-Base.repo.j2 dest=/etc/yum.repos.d/Centos-Base.repo owner=root group=root mode=0644

  - name: Copy local epel repo
    template: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo owner=root group=root mode=0644

  # http://mirror.pnl.gov/epel/RPM-GPG-KEY-EPEL-6
  - name: Add EPEL GPG key
    copy: src=RPM-GPG-KEY-EPEL-7  
          dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7 
          owner=root
          group=root
          mode=0644

  - name: Disable fastest mirror plugin
    lineinfile: dest=/etc/yum/pluginconf.d/fastestmirror.conf regexp=^enabled line='enabled = 0'

   #installeren van bash,bind,git,nano,tree,vim,wget
   - name: install packages
     apt: name={{ item }} update_cache=yes state=latest
     with_items:
       - bash-completion
       - bind-utils
       - git
       - nano
       - tree
       - vim-enhanced
       - wget
   
   #Gebruiken voor jezelf aanmaken
   - name: Create a user
       user: dylano
       password: 'admin'
       group: admin
       groups: sudo
       state: present
       shell: /bin/bash
       system: no
       createhome: yes
       home: /home/dylano

   #Genereer een SSH-key    
   - name: create 2048 bits ssh key
     user:
      name: dylano
      generate_ssh_keys: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa


    #enable firewall voor http,https en ip 
  #- firewalld:
    #source: 192.0.2.0/24
    #zone: internal
    #state: enabled

  #- firewalld:
   #zone: dmz
    #service: http
    #permanent: true
    #state: enabled   

  #- firewalld:
   # service: https
    #permanent: true
    #state: enabled