# group_vars/all.yml
# Variables visible to all nodes
#ERROR: Host_vars word niet afgelopen voor variabelenµ
#gevonden door te kijken of deze items werden toegevoegd bij de provision 
#en bij uitvoeren commando firewall-cmd --list-all
#kreeg ik bevestiging dat deze niet toegevoegd werden
---

#repo's en packages installen
rhbase_repositories: 
  - epel-release

rhbase_install_packages: 
  - bash-completion, bash-completion-extras
  - bind, bind-utils
  - git
  - nano
  - tree
  - vim-enhanced
  - wget

# Usersvagr
# MD5-encryptie
rhbase_users: 
  - name: dylano
    password: '$1$mmHR2KDR$Bflb5h9Vh87PgO7atJhpZ0'
    groups: 
      - dylano
      - wheel
      - bind

#ssh key
rhbase_ssh_user: dylano
rhbase_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJhSZ4tTI9SENm6cmvRQ/K+uJGabjJyFrHpNWP9wjsmcL2W5SQD0XCI5YXlm/a0EqeOi2N36GtMU4KOIaiZzhIwn3sFdnDarHqU5dbE19Q3LPjyOSqOlDF8syo5tLzq3Q1bgahsuxqtoAzQqxCKquF+WZv/84H++e8AqIeW4WDKBpb2LOtTeKhDcFHokfxQM9jKFOIiEDi5+7TI8Cm2mt44cqnWXoz/fn3zJ5j/ytqr+xP8eCFFLEc9DlsmnXeUj/Oy4WeeH9HtobPtqPduLerkfdxyxhq18xLj7NpF4v8Pf9FxrzgbXcto25PMSXvXWWjaf7lze2uf6VQ3UD7FTyUB1U8lqEmzpm7MFuhZbQdSsjsUxGO5cEZnEEiPFIM+v/pqYU5yivQ2gy3eHKl946Ue+flqqCzVlo9moDdtmFokzpzfztuRun+N7eZ86F9+kI4qWEzCnDOMyHhzEBJLLjsI7jd1NHrFVpqsXlLxExHY2QT04fcjyQhF4HCd/EBfiNWVDQ8zfSbZIzTMXpeZnp5lq8Tv95T4RzventbX7av7leUCWuMAMFJPW7lE/z6u7lHlHTb2pZvJjWZb4A9JRr9NYdQq2l9Z1xK3NrtMJsvr0BHtcGwTReKHZn7w76ugQw1wK2Oxg0W/qPWl42KrJ3gVk+mku1mNt97AtWum1lybw== Dylan@DESKTOP-MNGUEC8

#nieuwe SSH laten generen want 'dylano' moet naar 'Dylan verander worden'
#MOTD
rhbase_motd: true
rhbase_dynamic_motd: true