# group_vars/all.yml
# Variables visible to all nodes
  
---

#repo's en packages installen
rhbase_enable_repos: epel
rhbase_repositories: epel-release

rhbase_install_packages: 
  - bash-completion
  - bind-utils
  - git
  - nano
  - tree
  - vim-enhanced
  - wget


# Users
# MD5-encryptie
rhbase_users: 
  - name: dylano
    password: '$1$mmHR2KDR$Bflb5h9Vh87PgO7atJhpZ0'
    groups: 
      - dylano
      - wheel
rhbase_user_groups: 
  - wheel

rhbase_ssh_allow_groups: 
  - wheel
  - dylano 
  - vagrant

#ssh key
rhbase_ssh_user: dylano
rhbase_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDb31E3t+Sk3jqn+rEF5PMlLsKu64Gvcuyx/K/JEVYz2YmCLRoGJUrEKSKVxPtPsccPBM4p4g8UIKF45zzCeYEBTVa0oiOuvP6eGS6TlpwFWLxvNI/RKNX1/WDUHkUy++K/h3gn+A6Cndpq3E9aXUTrpfWsUiPSfFC9GeNSRNoYVBM5eeY0rAfDGH56n3corGIS59SKAVJwHiv0xsDcv+YhSwhogI9j6HEUfmf+INDAsSkShNs6mGEWeYe6vRayZnRh4PV4MqFyjt039/VczlbU48DIe3RCZhE5oXJ6HcdbMDCs/0KaC3Fsaiiie//ALfbGiWaPgQJg9WLwcc/cYDml4A9Arq7f2tzSHy+HdUhRv7OccJP63KRsaTjfUT5WOfLFAy33Bvp/no8Z0leslzeJpSYaVpaPH/jRy05i0okhl/PxIBRMFIPs/aAiksJvyTIu94GVVK86IWFaiukbeLbZjJjhVCsExhVCP84ebNk+UgHDc6rvsExM8MVuXDn5XI6/u5lp+I7Mr2Tkxo9lsCWTLBz4V5UPrWEVRlDgX0exhGWVlVRqTLsJARKk37LEBxSDzYi1kobwtliSmNBbK2sO5kryd6O36QHb0FMmKOmzgaNlDeMuCdDFq1MVvxff3n6LcMx7vh/RDoc+N4U4kVY45+nKzOBFMue9XsNQSV8Fjw== dylano.steenhuyzen@hotmail.com"
#nieuwe SSH laten generen want 'dylano' moet naar 'Dylan verander worden'
#MOTD
rhbase_motd: true
rhbase_dynamic_motd: true