# roles/rhbase/tasks/users.yml
#
# Create groups and users on the system
---
- name: Users | Process groups
  set_fact:
    rhbase_user_groups: "{{ rhbase_user_groups }} + {{ item.groups }}"
  with_items: "{{ rhbase_users }}"
  tags:
    - rhbase
    - users

- name: Users | Add groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ rhbase_user_groups | unique }}"
  tags:
    - rhbase
    - users
#12/10: encryptie vereist van passwoord:
#password: "{{ my_password | password_hash('sha512') }}"
- name: Users | Add users
  user:
    name: "{{ item.name }}"
    state: present
    comment: "{{ item.comment|default('') }}"
    shell: "{{ item.shell|default('/bin/bash') }}"
    groups: "{{ ','.join(item.groups) if item.groups is defined else '' }}"
    password: "{{ item.password | password_hash('sha512') }}"
  with_items: "{{ rhbase_users }}"
  tags:
    - rhbase
    - users

#SSH keys genereren op host systeem:
 # - name: Generate /etc/ssh/ RSA host key
   # command : ssh-keygen -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C "" -N ""
    #args:
    # creates: /etc/ssh/ssh_host_rsa_key



- name: "Users | Set up SSH key for user {{ rhbase_ssh_user|default('(not specified)') }}"
  authorized_key:
    user: "{{ rhbase_ssh_user }}"
    key: "{{ lookup('file', '/home/dylano/.ssh/id_rsa.pub') }}"
    state: present
  when: rhbase_ssh_user is defined
  tags:
    - rhbase
    - users
