# site.yml
##ERROR##
# Probleem: fout bij plaatsen van de certificaten:
#           "Destination directory /etc/pki/tls/private//vagrant/ansible/certificates does not exist"
# Oplossing: pre taak die deze al naar de juiste folder zet
---
#oplossing voor SSH error: 
#de 'all' host initialiseren laat me ssh dylano@192.0.2.10 doen
- hosts: all
  become: true
  roles:
    - bertvv.rh-base
## Webserver ##
- hosts: pu001
  become: true
  roles: 
    - bertvv.rh-base
    - bertvv.mariadb
    - bertvv.httpd
    - bertvv.wordpress
## mailserver ## 
- hosts: pu002
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.mailserver
## dns_masterserver ##
- hosts: pr001
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.bind
## dns_slaveserver ##
- hosts: pr002
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.bind
## fileshareserver ##
- hosts: pr011
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.samba
    - bertvv.vsftpd
## dhcpserver ##
- hosts: pr003
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.dhcp
  