# site.yml
##ERROR##
# Probleem: fout bij plaatsen van de certificaten:
#           "Destination directory /etc/pki/tls/private//vagrant/ansible/certificates does not exist"
# Oplossing: pre taak die deze al naar de juiste folder zet
---
#oplossing voor SSH error: 
#de 'all' host initialiseren laat me ssh dylano@192.0.2.10 doen
- hosts: all
  become: true
  roles:
    - bertvv.rh-base
## Webserver ##
- hosts: pu001
  become: true
  roles: 
    - bertvv.rh-base
    - bertvv.mariadb
    - bertvv.httpd
    - bertvv.wordpress
 
- hosts: pu002
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.mailserver

- hosts: pr001
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.bind

- hosts: pr002
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.bind